---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: dockerkubapp
        image: hokipoki123/dockerkub:2.0.9
        ports:
        - containerPort: 80
